import type { NextPage } from "next";
import Head from "next/head";
import PaginatedItems from "../src/components/PaginatedItems";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rick and Morty Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PaginatedItems itemsPerPage={12} />
      </main>
    </>
  );
};

export default Home;
