import type { NextPage } from "next";
import Head from "next/head";
import CharactersCatalog from "../src/components/CharactersCatalog";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rick and Morty Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CharactersCatalog />
      </main>
    </>
  );
};

export default Home;
